
GET http://localhost:8000/ok/
###
GET http://eveapi.azurewebsites.net/withStatusCatalog
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/stateWithColumns
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/addressWithOrders
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE 
###
GET http://eveapi.azurewebsites.net/commentWithUsers
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/categoryWithMenuItems
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE

###
GET http://eveapi.azurewebsites.net/restaurantIdBetween?id1=1,id2=3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/quantityRange?quantity1=2&quantity2=3
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE 
###
GET https://eveapi.azurewebsites.net/emailVerifiedTrue
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/orderCarYear
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE 
###
GET http://eveapi.azurewebsites.net/limitAddress?limit=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/cityNames?cityName=n
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/orderPrice?price=500
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/restaurantAndOwners
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/comment
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/driver/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://eveapi.azurewebsites.net/menuItem
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
GET http://localhost:8000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzMDU5NzB9.4CrE6eMEI3tSDoLGd478sbcLZhYoAn7exHm_BiAKOus
###
GET http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzMDU5NzB9.4CrE6eMEI3tSDoLGd478sbcLZhYoAn7exHm_BiAKOus
###
put http://localhost:8000/users/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE

{
 "name": "wanjiru",
    "contact_phone": "+254187324234",
    "phone_verified":true,
    "email":"evamso@gmail.com",
    "email_verified":false,
    "confirmation_code":"w8376",
    "password":"564748494",
    "address": "Nairobi, Kenya"
}
###
DELETE http://localhost:8000/users/10
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
###
POST http://localhost:8000/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
Content-Type: application/json

{
   
    "name": "edwin",
    "contact_phone": "+254187324234",
    "phone_verified":true,
    "email":"edwin@gmail.com",
    "email_verified":true,
    "confirmation_code":"8376",
    "password":"8494"
}
###
GET  http://localhost:8000/comment
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzM3NTJ9.DHzqUG10ulvKllV-2skogNTVSxaOv_Vhiqw-2tQgMok
###
POST http://localhost:8000/comment
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnYXQjQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzE4MzczOTk3fQ.wRzPj6vNNujpfntoJNm-yrReisyralE7W4ieF3tqid0
Content-Type: application/json

{
    "comment_text":"was yummy",
    "is_complaint": false,
    "is_praise": true,
    "created_at":"2023-5-4",
    "updated_at":"2024-1-23",
    "order_id": 2,
    "user_id": 2
}

###
POST http://localhost:8000/orderMenuItem
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE
Content-Type: application/json

{
   
   "quantity": 3,
    "item_price": 650,
    "price":2100,
   "order_id": 2,
    "menu_item_id":2
}
###
POST http://localhost:8000/address
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXJlbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MTgzNzA3MDl9.2MNPQX5C7--lQx2gTqzBfUnRHBsWKyhasMUIF-8WxsE 
Content-Type: application/json

{
   
    "street_address_1":" 3456trrgh",
    "street_address_2": "23rerfd",
   "zip_code":"dfgfe345",
   "delivery_instructions": "to house 101",
    "created_at":"2023-3-4",
   "updated_at":"2023-5-6",
    "user_id":3,
    "city_id": 1
}

###
POST http://localhost:8000/register
Content-Type: application/json

{
     "userId":4,
     "email":"gat#@gmail.com",
    "password":"4567",
    "role":"user"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email":"gat#@gmail.com",
    "password":"4567"
}